{
 "title": "Air Quality",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval_multiplier", "label": "Interval Multiplier", "query": "1" }
  ]
 },
 "panels": [
  { "title": "DB Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PG Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  substring(version() from 'PostgreSQL ([0-9]+\\.[0-9]+)') AS postgres,\n  extversion AS timescaledb\nFROM pg_extension\nWHERE extname = 'timescaledb';\n"
    }
   ]
  },
  {
   "title": "TSDB Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  substring(version() from 'PostgreSQL ([0-9]+\\.[0-9]+)') AS postgres,\n  extversion AS timescaledb\nFROM pg_extension\nWHERE extname = 'timescaledb';\n"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size('postgres')\n-- SELECT pg_size_pretty(pg_database_size('postgres'))"
    }
   ]
  },
  {
   "title": "TimescaleDB",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT hypertable_name, hypertable_size(format('%I.%I', hypertable_schema, hypertable_name)::regclass) as size_in_mb, approximate_row_count(hypertable_schema || '.' || hypertable_name) as rows, compression_enabled as compressed, num_chunks as chunks\nFROM timescaledb_information.hypertables;"
    }
   ]
  },
  { "title": "Air Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket((interval '$__interval') * $interval_multiplier, \"time\") AS time,\n       avg(temp) AS avg_temp\nFROM awair_sensor_data\nWHERE deviceid = '117' AND \"time\" >= $__timeFrom() AND \"time\" <= $__timeTo()\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT time_bucket((interval '$__interval') * $interval_multiplier, \"time\") AS time,\n       avg(temp) AS avg_temp\nFROM awair_sensor_data\nWHERE deviceid = '19796' AND \"time\" >= $__timeFrom() AND \"time\" <= $__timeTo()\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket((interval '$__interval') * $interval_multiplier, \"time\") AS time,\n       avg(humid) AS avg_humid\nFROM awair_sensor_data\nWHERE deviceid = '117' AND \"time\" >= $__timeFrom() AND \"time\" <= $__timeTo()\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT time_bucket((interval '$__interval') * $interval_multiplier, \"time\") AS time,\n       avg(humid) AS avg_humid\nFROM awair_sensor_data\nWHERE deviceid = '19796' AND \"time\" >= $__timeFrom() AND \"time\" <= $__timeTo()\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket((interval '$__interval') * $interval_multiplier, \"time\") AS time,\n       avg(co2) AS avg_co2\nFROM awair_sensor_data\nWHERE deviceid = '117' AND \"time\" >= $__timeFrom() AND \"time\" <= $__timeTo()\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT time_bucket((interval '$__interval') * $interval_multiplier, \"time\") AS time,\n       avg(co2) AS avg_co2\nFROM awair_sensor_data\nWHERE deviceid = '19796' AND \"time\" >= $__timeFrom() AND \"time\" <= $__timeTo()\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "VOC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket((interval '$__interval') * $interval_multiplier, \"time\") AS time,\n       avg(voc) AS avg_voc\nFROM awair_sensor_data\nWHERE deviceid = '117' AND \"time\" >= $__timeFrom() AND \"time\" <= $__timeTo()\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT time_bucket((interval '$__interval') * $interval_multiplier, \"time\") AS time,\n       avg(voc) AS avg_voc\nFROM awair_sensor_data\nWHERE deviceid = '19796' AND \"time\" >= $__timeFrom() AND \"time\" <= $__timeTo()\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket((interval '$__interval') * $interval_multiplier, \"time\") AS time,\n       avg(pm25) AS avg_pm25\nFROM awair_sensor_data\nWHERE deviceid = '117' AND \"time\" >= $__timeFrom() AND \"time\" <= $__timeTo()\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT time_bucket((interval '$__interval') * $interval_multiplier, \"time\") AS time,\n       avg(pm25) AS avg_pm25\nFROM awair_sensor_data\nWHERE deviceid = '19796' AND \"time\" >= $__timeFrom() AND \"time\" <= $__timeTo()\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}