{
 "title": "Air Quality",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval_multiplier", "label": "Interval Multiplier", "query": "1" }
  ]
 },
 "panels": [
  { "title": "Air Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', \"time\") as \"time\",\n  devicename,\n  avg(temp) AS avg_val\nFROM awair_sensor_data\nWHERE\n  time >= $__timeFrom() AND time <= $__timeTo()\nGROUP BY\n  time_bucket('$__interval', \"time\"),\n  devicename\nORDER BY\n  \"time\" ASC\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', \"time\") as \"time\",\n  devicename,\n  avg(humid) AS avg_val\nFROM awair_sensor_data\nWHERE\n  time >= $__timeFrom() AND time <= $__timeTo()\nGROUP BY\n  time_bucket('$__interval', \"time\"),\n  devicename\nORDER BY\n  \"time\" ASC\n"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', \"time\") as \"time\",\n  devicename,\n  avg(co2) AS avg_val\nFROM awair_sensor_data\nWHERE\n  time >= $__timeFrom() AND time <= $__timeTo()\nGROUP BY\n  time_bucket('$__interval', \"time\"),\n  devicename\nORDER BY\n  \"time\" ASC\n"
    }
   ]
  },
  {
   "title": "Bedroom",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n    -- deviceid,\n    devicename,\n    LAST(temp, time) AS temp,\n    LAST(humid, time) AS humid,\n    LAST(co2, time) AS co2,\n    LAST(voc, time) AS voc,\n    LAST(pm25, time) AS pm25\nFROM \n    awair.awair_sensor_data\nWHERE devicename = 'Bedroom'\nGROUP BY \n    devicename\n"
    }
   ]
  },
  {
   "title": "VOC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', \"time\") as \"time\",\n  devicename,\n  avg(voc) AS avg_val\nFROM awair_sensor_data\nWHERE\n  time >= $__timeFrom() AND time <= $__timeTo()\nGROUP BY\n  time_bucket('$__interval', \"time\"),\n  devicename\nORDER BY\n  \"time\" ASC\n"
    }
   ]
  },
  {
   "title": "PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', \"time\") as \"time\",\n  devicename,\n  avg(pm25) AS avg_val\nFROM awair_sensor_data\nWHERE\n  time >= $__timeFrom() AND time <= $__timeTo()\nGROUP BY\n  time_bucket('$__interval', \"time\"),\n  devicename\nORDER BY\n  \"time\" ASC\n"
    }
   ]
  },
  {
   "title": "Living Room",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n    -- deviceid,\n    devicename,\n    LAST(temp, time) AS temp,\n    LAST(humid, time) AS humid,\n    LAST(co2, time) AS co2,\n    LAST(voc, time) AS voc,\n    LAST(pm25, time) AS pm25\nFROM \n    awair.awair_sensor_data\nWHERE devicename = 'Living Room'\nGROUP BY \n    devicename\n"
    }
   ]
  },
  {
   "title": "Office",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n    -- deviceid,\n    devicename,\n    LAST(temp, time) AS temp,\n    LAST(humid, time) AS humid,\n    LAST(co2, time) AS co2,\n    LAST(voc, time) AS voc,\n    LAST(pm25, time) AS pm25\nFROM \n    awair.awair_sensor_data\nWHERE devicename = 'Office'\nGROUP BY \n    devicename\n"
    }
   ]
  }
 ]
}