{
 "title": "HealthKit",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Weight",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value FROM healthkit.bodymass WHERE $__timeFilter(time) ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Body Fat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, (value * 100) AS bodyfatpercentage\nFROM healthkit.bodyfatpercentage\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Steps Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Steps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    time_bucket('1 day', time) AS \"time\", \n    SUM(value) AS \"Step Count\"\nFROM \n    healthkit.stepcount\nWHERE \n    $__timeFilter(time)\nGROUP BY \n    1\nORDER BY \n    \"time\" ASC\n"
    }
   ]
  },
  {
   "title": "Slept Last Night",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  DATE_TRUNC('day', time - INTERVAL '5 hour') + INTERVAL '5 hour' AS \"Time\", \n  SUM(EXTRACT(EPOCH FROM (enddate - time))) AS \"Hours Slept\"\nFROM \n  sleepanalysis\nWHERE \n  source = 'Oura'\n  AND $__timeFilter(time) \n  AND value = 1\nGROUP BY \n  \"Time\"\nORDER BY \n  \"Time\" ASC;\n"
    }
   ]
  },
  {
   "title": "Sleep per Night",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  DATE_TRUNC('day', time - INTERVAL '5 hour') + INTERVAL '5 hour' AS \"Time\", \n  SUM(EXTRACT(EPOCH FROM (enddate - time))) AS \"Hours Slept\"\nFROM \n  sleepanalysis\nWHERE \n  source = 'Oura'\n  AND $__timeFilter(time) \n  AND value = 1\nGROUP BY \n  \"Time\"\nORDER BY \n  \"Time\" ASC;\n"
    }
   ]
  },
  {
   "title": "Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "steps" } },
   "targets": [
    {
     "rawSql": "SELECT \n    time_bucket('1 day', time) AS \"time\", \n    SUM(value) AS \"Step Count\"\nFROM \n    healthkit.stepcount\nWHERE \n    $__timeFilter(time)\nGROUP BY \n    1\nORDER BY \n    \"time\" ASC\n"
    }
   ]
  },
  {
   "title": "Headphone Audio Exposure",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  enddate,\n  value,\n  source\nFROM healthkit.headphoneaudioexposure\n"
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select * from \"healthkit\".\"heartrate\" WHERE $__timeFilter(time) ORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Sleep Analysis",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \n  time, \n  enddate, \n  source as \"Text\", \n  value\nFROM sleepanalysis"
    }
   ]
  }
 ]
}