{
 "title": "Money",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Spending Categories",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT category, \n       SUM(amountinusd) as total_amount \nFROM money.transactions \nWHERE \n    $__timeFilter(time) \n    AND (NOT category ILIKE '%Transfer%')\n    AND (NOT name ILIKE '%CAPITAL ONE AUTOPAY%')\n    AND amountinusd >= 0 \nGROUP BY category \nORDER BY total_amount DESC;\n"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "table",
   "gridPos": { "h": 29, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(time::date, 'YYYY-MM-DD') as date, institution, name, category, amountinusd \nFROM money.transactions \nWHERE $__timeFilter(time) \nORDER BY date DESC;\n"
    }
   ]
  },
  {
   "title": "Net Worth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "-- SELECT \"time\", SUM(currentinusd) as \"Net Worth\"\n-- FROM money.balances\n-- GROUP BY \"time\"\n-- ORDER BY \"time\";\n\n-- SELECT * FROM money.balances\n\nSELECT \"time\", \nSUM(\n    CASE \n        WHEN \"type\" = 'credit_card' THEN -currentinusd\n        ELSE currentinusd\n    END\n) as \"Net Worth\"\nFROM money.balances\nGROUP BY \"time\"\nORDER BY \"time\" ASC;\n"
    }
   ]
  },
  {
   "title": "Spending Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \n    time_bucket('1 day', time) AS \"time\", \n    SUM(amountinusd) AS \"Money Spent\"\nFROM money.transactions\nWHERE $__timeFilter(time)\nAND (NOT category ILIKE '%Transfer%')\nAND (NOT name ILIKE '%CAPITAL ONE AUTOPAY%')\nAND amountinusd >= 0\nGROUP BY \"time\"\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Spending History",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \n    time_bucket('1 day', time) AS \"time\", \n    SUM(amountinusd) AS \"Money Spent\"\nFROM money.transactions\nWHERE $__timeFilter(time)\nAND (NOT category ILIKE '%Transfer%')\nAND (NOT name ILIKE '%CAPITAL ONE AUTOPAY%')\nAND amountinusd >= 0\nGROUP BY \"time\"\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Account Balances",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \n    CASE \n    WHEN accountid = 'A4kJ7zO4gOU63a6AJ9vpC6MaE7EmdatMv9Eg6' THEN 'Ally Bank'\n    WHEN accountid = 'yy10NJaywaiJ3RJzX4x9sYn7MNM1b7spKMn1K' THEN 'Ally Bank'\n    WHEN accountid = 'K7gxEzq7pqFQowQ894gvILZKJkJz7KFEeXBYZ' THEN 'Ally Bank'\n    WHEN accountid = 'kYkNBq1Y71uqOKqVNodkUJ7mZ4Z0ymCorjAw9' THEN 'Ally Bank'\n    WHEN accountid = 'vq6PY4jqNjsQZoQVe06kIN7eM3M4reCV98dNV' THEN 'Ally Bank'\n    WHEN accountid = 'acc_oi0gk7ogfo887j83nm000' THEN 'Capital One'\n    WHEN accountid = 'Yepkqg1A06fP9YY1o46yH6pdjDZ0ZvtzVM6Na' THEN 'Acorns'\n    WHEN accountid = 'eOM57P1od3iaMbb0OK78fEr1yqg7gLC4V3vM6' THEN 'Acorns'\n    WHEN accountid = 'vXJRAgz98vT5Qp6xy3EZSJ99Jq3yABfVBOdpM' THEN 'Wise'\n    WHEN accountid = 'Aowvr8je1Qh06dvV1j73TOppOy71LNHMk8Ewk' THEN 'Wise'\n\n    WHEN accountid = 'K1JD8Pbe0BuXQygVYaPota57jP3vd5hEZ3Byy' THEN 'Wise'\n    WHEN accountid = 'kQzr6ym4ALt7q0d3waZOT5qyAKdExqto4xAbv' THEN 'Wise'\n    WHEN accountid = 'Aowvr8je1Qh06dvV1j73TOpdvQg5XpiMk8Ewb' THEN 'Wise'\n    WHEN accountid = 'yQgmj4zY8rtEJ1xZqQd3TXKbZz4BxKUpLknRp' THEN 'Wise'\n    WHEN accountid = '3KjgLn65BJtd8JbZx7rDUbkLoA5yEkHoeYjPK' THEN 'Wise'\n    -- Add more WHEN conditions for each unique accountId\n    ELSE accountid\n    END as account,\n    institution as name,\n    currency,\n    CASE \n        WHEN \"type\" = 'credit_card' THEN -current\n        ELSE current\n    END as amount,\n    CASE \n        WHEN \"type\" = 'credit_card' THEN -currentinusd\n        ELSE currentinusd\n    END as inusd\nFROM money.balances\nWHERE time = (SELECT MAX(time) FROM money.balances);\n"
    }
   ]
  },
  {
   "title": "Net Worth Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- SELECT \"time\", SUM(currentinusd) as \"Net Worth\"\n-- FROM money.balances\n-- GROUP BY \"time\"\n-- ORDER BY \"time\";\n\n-- SELECT * FROM money.balances\n\nSELECT \"time\", \nSUM(\n    CASE \n        WHEN \"type\" = 'credit_card' THEN -currentinusd\n        ELSE currentinusd\n    END\n) as \"Net Worth\"\nFROM money.balances\nGROUP BY \"time\"\nORDER BY \"time\";\n"
    }
   ]
  }
 ]
}