{
 "title": "ScreenTime",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Apple ScreenTime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ScreenTime Mac",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT app_name, EXTRACT(EPOCH FROM SUM(time_end - time)) AS total_usage\nFROM app_usage.apple_screen_time_data\nWHERE device_id = 'NOTFOUND'\nAND $__timeFilter(time)\nGROUP BY app_name\nORDER BY total_usage DESC\n\n-- SELECT app_name, EXTRACT(EPOCH FROM SUM(time_end - time)) AS total_usage\n-- FROM app_usage.apple_screen_time_data\n-- WHERE device_name IS NULL\n-- -- AND time >= NOW() - INTERVAL '24 hours'\n-- AND $__timeFilter(time)\n-- GROUP BY app_name\n-- ORDER BY total_usage DESC"
    }
   ]
  },
  {
   "title": "ScreenTime iOS",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT app_name, EXTRACT(EPOCH FROM SUM(time_end - time)) AS total_usage\nFROM app_usage.apple_screen_time_data\nWHERE device_name = 'iPhone13,3'\nAND $__timeFilter(time)\nGROUP BY app_name\nORDER BY total_usage DESC"
    }
   ]
  },
  {
   "title": "ScreenTime Mac",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "rawSql": "SELECT app_name, EXTRACT(EPOCH FROM SUM(time_end - time)) AS total_usage\nFROM app_usage.apple_screen_time_data\nWHERE device_id = 'NOTFOUND'\nAND $__timeFilter(time)\nGROUP BY app_name\nORDER BY total_usage DESC \nLIMIT 10"
    }
   ]
  },
  {
   "title": "ScreenTime iOS",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "rawSql": "SELECT app_name, EXTRACT(EPOCH FROM SUM(time_end - time)) AS total_usage\nFROM app_usage.apple_screen_time_data\nWHERE device_name = 'iPhone13,3'\nAND $__timeFilter(time)\nGROUP BY app_name\nORDER BY total_usage DESC \nLIMIT 10"
    }
   ]
  },
  {
   "title": "ScreenTime Mac",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "-- SELECT time, time_end, app_name, (time_end - time) AS duration\n-- FROM app_usage.apple_screen_time_data\n-- WHERE device_id = 'NOTFOUND'\n-- AND $__timeFilter(time)\n\nSELECT time, time_end, app_name, (time_end - time) AS duration\nFROM app_usage.apple_screen_time_data\nWHERE device_id = 'NOTFOUND'\nAND $__timeFilter(time)\nAND app_name IN (\n  SELECT app_name\n  FROM (\n    SELECT app_name, SUM(time_end - time) AS total_usage\n    FROM app_usage.apple_screen_time_data\n    WHERE device_id = 'NOTFOUND'\n    AND $__timeFilter(time)\n    GROUP BY app_name\n    ORDER BY total_usage DESC\n    LIMIT 10\n  ) AS subquery\n)\n"
    }
   ]
  },
  {
   "title": "ScreenTime iOS",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "-- SELECT time, time_end, app_name, device_name\n-- FROM app_usage.apple_screen_time_data\n-- WHERE device_name = 'iPhone13,3'\n\n-- AND $__timeFilter(time) \nSELECT time, time_end, app_name, device_name\nFROM app_usage.apple_screen_time_data\nWHERE device_name = 'iPhone13,3'\nAND $__timeFilter(time) \nAND app_name IN (\n  SELECT app_name\n  FROM (\n    SELECT app_name, SUM(time_end - time) AS total_usage\n    FROM app_usage.apple_screen_time_data\n    WHERE device_name = 'iPhone13,3'\n    AND $__timeFilter(time)\n    GROUP BY app_name\n    ORDER BY total_usage DESC\n    LIMIT 10\n  ) AS subquery\n)\n"
    }
   ]
  },
  {
   "title": "Activity Watch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "ActivityWatch Mac",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "targets": [
      {
       "rawSql": "SELECT app_name, EXTRACT(EPOCH FROM SUM(time_end - time)) AS total_usage\nFROM app_usage.aw_window_event_data\nWHERE $__timeFilter(time) AND app_name != 'loginwindow'\nGROUP BY app_name\nORDER BY total_usage DESC"
      }
     ]
    },
    {
     "title": "ScreenTime WEB Mac",
     "type": "marcusolsson-gantt-panel",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "rawSql": "SELECT time, time_end, \n'URL' as did,\nSUBSTRING(url FROM 'https?://([^/]*)') AS domain\nFROM app_usage.aw_web_event_data\nWHERE $__timeFilter(time)\n"
      }
     ]
    }
   ]
  }
 ]
}