{
 "title": "Server and Docker",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", n_containers || '/' || n_containers_running as running FROM docker ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "-- SELECT \"time\", interface, bytes_sent FROM net WHERE interface NOT IN ('all') ORDER BY \"time\" ASC\n-- SELECT \"time\", bytes_sent - LAG(bytes_sent) OVER (ORDER BY \"time\") AS bytes_sent_diff FROM net WHERE interface NOT IN ('all', 'eth0') ORDER BY \"time\" DESC\n-- SELECT time, interface, bytes_sent, bytes_recv from net ORDER BY time DESC\n\nSELECT \"time\", interface, bytes_sent - lag(bytes_sent, 1, 0) OVER (PARTITION BY interface ORDER BY \"time\") AS bytes_tx\nFROM net WHERE interface NOT IN ('all', 'lo')\nORDER BY \"time\" ASC"
    },
    {
     "rawSql": "-- SELECT \"time\", interface, bytes_recv *-1 as bytes_recv FROM net WHERE interface NOT IN ('all') ORDER BY \"time\" DESC \n-- SELECT \"time\", (bytes_recv - LAG(bytes_recv) OVER (ORDER BY \"time\")) * -1  AS bytes_recv_diff FROM net WHERE interface NOT IN ('all') ORDER BY \"time\" DESC\n-- SELECT \"time\", interface, (bytes_recv * -1) as bytes_recv FROM net WHERE interface NOT IN ('all') ORDER BY \"time\" ASC\n\nSELECT \"time\", interface, (bytes_recv - lag(bytes_recv, 1, 0) OVER (PARTITION BY interface ORDER BY \"time\")) * -1 AS bytes_rx\nFROM net WHERE interface NOT IN ('all', 'lo')\nORDER BY \"time\" ASC\n"
    }
   ]
  },
  {
   "title": "PG Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  substring(version() from 'PostgreSQL ([0-9]+\\.[0-9]+)') AS postgres,\n  extversion AS timescaledb\nFROM pg_extension\nWHERE extname = 'timescaledb';"
    }
   ]
  },
  {
   "title": "TSDB Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  substring(version() from 'PostgreSQL ([0-9]+\\.[0-9]+)') AS postgres,\n  extversion AS timescaledb\nFROM pg_extension\nWHERE extname = 'timescaledb';"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size('postgres')\n-- SELECT pg_size_pretty(pg_database_size('postgres'))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", uptime FROM system WHERE uptime IS NOT NULL ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Hypertables",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT hypertable_name, hypertable_size(format('%I.%I', hypertable_schema, hypertable_name)::regclass) as size_in_mb, approximate_row_count(hypertable_schema || '.' || hypertable_name) as rows, compression_enabled as compressed, num_chunks as chunks\nFROM timescaledb_information.hypertables;"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", usage_active as CPU_use, cpu FROM cpu WHERE usage_active IS NOT NULL AND cpu = 'cpu-total' ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, (100 - available_percent) as memory FROM mem WHERE available_percent IS NOT NULL ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, path, used_percent FROM disk WHERE used_percent IS NOT NULL AND path = '/' ORDER BY time DESC LIMIT 1\n-- select * from disk"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", host, (swap_total - swap_free) as swap_used FROM mem ORDER BY \"time\" DESC LIMIT 1 "
    },
    {
     "rawSql": "SELECT \"time\", host FROM mem LIMIT 50 "
    }
   ]
  },
  {
   "title": "All Tables",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  relname AS table_name,\n  pg_size_pretty(pg_total_relation_size(relid)) AS table_size\nFROM\n  pg_stat_user_tables\nORDER BY\n  pg_total_relation_size(relid) DESC;\n"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', \"time\") as \"time\",\n  cpu,\n  avg(usage_active) as active\nFROM cpu\nWHERE\n  cpu = 'cpu-total' AND\n  time >= $__timeFrom() AND time <= $__timeTo()\nGROUP BY\n  time_bucket('$__interval', \"time\"), cpu\nORDER BY\n  \"time\" ASC\n"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', \"time\") as \"time\",\n  avg(total) as total,\n  avg(available) as available\nFROM mem\nWHERE\n  total IS NOT NULL AND\n  time >= $__timeFrom() AND time <= $__timeTo()\nGROUP BY\n  time_bucket('$__interval', \"time\")\nORDER BY\n  \"time\" ASC\n"
    }
   ]
  },
  {
   "title": "Disk Space GB",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', \"time\") as \"time\",\n  device::text AS \"metric\",\n  AVG(used) AS \"used\"\nFROM disk\nWHERE\n  $__timeFilter(time) AND\n  device NOT IN ('iCloud', 'Home', 'Dropbox')\nGROUP BY\n  time_bucket('$__interval', \"time\"), device\nORDER BY\n  \"time\" ASC\n"
    },
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', \"time\") as \"time\",\n  path,\n  AVG(total) as total\nFROM disk\nWHERE \n  path = '/' AND\n  time >= $__timeFrom() AND time <= $__timeTo()\nGROUP BY\n  time_bucket('$__interval', \"time\"), path\nORDER BY\n  \"time\" ASC\n"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', \"time\") as \"time\",\n  AVG(swap_total - swap_free) as swap_used\nFROM mem\nWHERE \n  time >= $__timeFrom() AND time <= $__timeTo() \nGROUP BY\n  time_bucket('$__interval', \"time\")\nORDER BY\n  \"time\" ASC\n"
    },
    {
     "rawSql": "SELECT\n  time_bucket('$__interval', \"time\") as \"time\",\n  AVG(swap_total) as swap_total\nFROM mem\nWHERE \n  time >= $__timeFrom() AND time <= $__timeTo() \nGROUP BY\n  time_bucket('$__interval', \"time\")\nORDER BY\n  \"time\" ASC\n"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "-- SELECT \"time\", container_name, usage_percent as cpu FROM docker_container_cpu ORDER BY \"time\" ASC \n\nSELECT\n  time_bucket('$__interval', \"time\") as \"time\",\n  container_name,\n  avg(usage_percent) AS cpu_usage\nFROM docker_container_cpu\nWHERE\n  time >= $__timeFrom() AND time <= $__timeTo()\nGROUP BY\n  time_bucket('$__interval', \"time\"),\n  container_name\nORDER BY\n  \"time\" ASC\n"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "-- SELECT time, container_name, usage_percent FROM docker_container_mem ORDER BY time ASC\n\nSELECT\n  time_bucket('$__interval', \"time\") as \"time\",\n  container_name,\n  avg(usage_percent) AS mem_usage\nFROM docker_container_mem\nWHERE\n  time >= $__timeFrom() AND time <= $__timeTo()\nGROUP BY\n  time_bucket('$__interval', \"time\"),\n  container_name\nORDER BY\n  \"time\" ASC\n"
    }
   ]
  },
  {
   "title": "Garbage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space %",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 52 },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  device::text AS \"metric\",\n  AVG(used_percent) AS \"used\"\nFROM disk\nWHERE $__timeFilter(time) AND device NOT IN ('iCloud', 'Home', 'Dropbox')\nGROUP BY 1,2\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Status",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 12, "x": 4, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \"time\", usage_active as cpu_, cpu FROM cpu WHERE usage_active IS NOT NULL AND cpu = 'cpu-total' ORDER BY time DESC LIMIT 1"
      },
      {
       "rawSql": "SELECT time, (100 -available_percent) as memory FROM mem WHERE available_percent IS NOT NULL ORDER BY time DESC LIMIT 1"
      },
      {
       "rawSql": "SELECT time, path, used_percent as disk FROM disk WHERE used_percent IS NOT NULL AND path = '/' ORDER BY time DESC LIMIT 1"
      }
     ]
    }
   ]
  }
 ]
}